spring.application.name=finance-dashboard

server.port=8081

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/personal_finance_db
spring.datasource.username=finance_user
spring.datasource.password=finance_password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
app.jwt.secret=${JWT_SECRET:FinanceDashboardLocalDevelopmentSecretKey123456789}
app.jwt.expiration=86400000